apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: seldon-model
spec:
  name: my-model-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: my-model
          image: nvakulenko/my-model:0.3
          #image: seldonio/mock_classifier:1.0
          #image-pull-policy: Never
    graph:
      children: []
      endpoint:
        type: REST
      name: my-model
      type: MODEL
    name: example
    replicas: 1